<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
         http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>be.everesst</groupId>
        <artifactId>parent</artifactId>
        <version>9.7.0</version>
    </parent>

    <groupId>com.cegeka.everesst.horizon.camis</groupId>
    <artifactId>sync-timesheet-parent</artifactId>
    <version>${revision}</version>
    <packaging>pom</packaging>

    <modules>
        <module>sync_timesheet</module>
        <module>sync_timesheet_application</module>
        <module>sync_timesheet_application_legacy</module>
        <module>sync_timesheet_logger</module>
        <module>sync_timesheet_shared</module>
        <module>sync_timesheet_web_client_factory</module>
        <module>sync_timesheet_workorder_access</module>
    </modules>

    <properties>
        <revision>1.0.0-sprint.161</revision>
        <thirdparty-dependencies.version>8.1.1</thirdparty-dependencies.version>

        <semver.skip>false</semver.skip>
        <opencsv.version>5.12.0</opencsv.version>
        <threeten-extra.version>1.7.2</threeten-extra.version>
        <json.version>20250517</json.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>be.everesst</groupId>
                <artifactId>thirdparty-dependencies</artifactId>
                <version>${thirdparty-dependencies.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>com.opencsv</groupId>
                <artifactId>opencsv</artifactId>
                <version>${opencsv.version}</version>
            </dependency>
            <dependency>
                <groupId>org.threeten</groupId>
                <artifactId>threeten-extra</artifactId>
                <version>${threeten-extra.version}</version>
            </dependency>
            <dependency>
                <groupId>org.json</groupId>
                <artifactId>json</artifactId>
                <version>${json.version}</version>
            </dependency>

            <dependency>
                <groupId>com.cegeka.everesst.horizon.camis</groupId>
                <artifactId>sync_timesheet_logger</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.cegeka.everesst.horizon.camis</groupId>
                <artifactId>sync_timesheet_application</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.cegeka.everesst.horizon.camis</groupId>
                <artifactId>sync_timesheet_shared</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.cegeka.everesst.horizon.camis</groupId>
                <artifactId>sync_timesheet</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.cegeka.everesst.horizon.camis</groupId>
                <artifactId>sync_timesheet_web_client_factory</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.cegeka.everesst.horizon.camis</groupId>
                <artifactId>sync_timesheet_workorder_access</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>com.cegeka.everesst.horizon.camis</groupId>
                <artifactId>sync_timesheet</artifactId>
                <version>${project.version}</version>
                <classifier>tests</classifier>
                <type>test-jar</type>
                <scope>test</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <executions>
                    <execution>
                        <id>test-jar</id>
                        <goals>
                            <goal>test-jar</goal>
                        </goals>
                        <configuration>
                            <skipIfEmpty>true</skipIfEmpty>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>